# Generated by Django 2.0.6 on 2018-06-14 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authhelper', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserEmailValidation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('validation_key', models.CharField(max_length=400)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('useremail', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='authhelper.UserEmail')),
            ],
        ),
    ]
