# Generated by Django 2.0.7 on 2018-07-19 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authhelper', '0004_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='special_scopes',
            field=models.CharField(default='', help_text='If multiple scope it must separated by comma', max_length=400),
        ),
    ]
