# Generated by Django 2.1.1 on 2018-12-10 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authhelper', '0005_auto_20180719_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='useremail',
            name='email_type',
            field=models.CharField(choices=[('office', 'Office'), ('home', 'Home'), ('mobile', 'Mobile'), ('emergency', 'Emergency')], default='office', max_length=10),
        ),
    ]
