# Generated by Django 2.1.5 on 2019-12-06 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authhelper', '0007_auto_20191203_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='credential_email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
