# Generated by Django 2.1.5 on 2022-04-04 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authhelper', '0008_userprofile_credential_email_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='invited_to_baza',
            field=models.BooleanField(default=False),
        ),
    ]
