# Generated by Django 2.1.5 on 2023-01-31 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authhelper', '0009_userprofile_invited_to_baza'),
    ]

    operations = [
        migrations.AddField(
            model_name='useremail',
            name='added_to_listmonk',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='useremail',
            name='listmonk_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='useremail',
            name='listmonk_uuid',
            field=models.UUIDField(null=True),
        ),
    ]
